/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./theme/components/Badge.vue')['default']
    'Bi:github': typeof import('~icons/bi/github')['default']
    Contributors: typeof import('./theme/components/Contributors.vue')['default']
    CopyRight: typeof import('./theme/components/CopyRight.vue')['default']
    CustomLink: typeof import('./theme/components/CustomLink.vue')['default']
    'EosIcons:modifiedDate': typeof import('~icons/eos-icons/modified-date')['default']
    'Fa6Solid:copyright': typeof import('~icons/fa6-solid/copyright')['default']
    'Fe:youtube': typeof import('~icons/fe/youtube')['default']
    NavCard: typeof import('./theme/components/NavCard.vue')['default']
    'Octicon:feedPerson16': typeof import('~icons/octicon/feed-person16')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
    Person: typeof import('./theme/components/person.vue')['default']
    'Ph:planetFill': typeof import('~icons/ph/planet-fill')['default']
    'RadixIcons:update': typeof import('~icons/radix-icons/update')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'SkillIcons:vercelDark': typeof import('~icons/skill-icons/vercel-dark')['default']
    'Tabler:brandBilibili': typeof import('~icons/tabler/brand-bilibili')['default']
    'Tabler:brandJuejin': typeof import('~icons/tabler/brand-juejin')['default']
    'Teenyicons:nextjsSolid': typeof import('~icons/teenyicons/nextjs-solid')['default']
    'Uiw:weixin': typeof import('~icons/uiw/weixin')['default']
  }
}
